# Generated by Django 3.2.8 on 2022-06-01 07:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('blog_title', models.CharField(default='', max_length=255, null=True)),
                ('blog_post', models.TextField(default='', max_length=10000, null=True)),
                ('blog_slug', models.CharField(default=api.models.getSlug, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('paste_bin', models.ImageField(upload_to='images')),
                ('blog_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('subject', models.CharField(default='', max_length=255, null=True)),
                ('message', models.TextField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='', max_length=25, null=True)),
                ('link_url', models.CharField(default='', max_length=255, null=True)),
                ('cover_image', models.ImageField(upload_to='images')),
                ('Tag', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
