# Generated by Django 3.1.2 on 2022-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220601_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_cover_image',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
