# Generated by Django 3.1.2 on 2022-06-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220601_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i_stock',
            name='slug',
        ),
    ]
