# Generated by Django 3.1.2 on 2022-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_i_stock_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i_stock',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
