# Generated by Django 3.1.2 on 2022-06-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220602_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Tag',
        ),
    ]
