# Generated by Django 3.1.2 on 2022-06-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_project_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='i_stock',
        ),
    ]
