# Generated by Django 3.1.2 on 2022-06-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220614_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_text', models.TextField(default='', max_length=10000, null=True)),
                ('homepage_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
